os: Visual Studio 2015

environment:
  matrix:
    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"

matrix:
  fast_finish: true

init:
  - ECHO "Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""

  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH% %HOME%"

build_script:
  - if "%PYTHON_VERSION%" == "3.6" set "BASE_PYTHON_VERSION=36"
  - if "%PYTHON_ARCH%" == "64" set "ARCH_LABEL=-x64"
  - set "CONDA_ROOT=C:\Miniconda%BASE_PYTHON_VERSION%%ARCH_LABEL%"
  - set "PATH=%CONDA_ROOT%;%CONDA_ROOT%\Scripts;%CONDA_ROOT%\Library\bin;%PATH%"
  - conda config --set always_yes yes
  - conda update conda --quiet
  - conda config --set auto_update_conda no
  - conda info
  - python -c "import sys; print(sys.version)"
  - python -c "import sys; print(sys.executable)"
  - python -c "import sys; print(sys.prefix)"
  - conda create -q -n timml_env python="%PYTHON_VERSION%" numpy scipy matplotlib mingw vc libpython
  - activate timml_env
  - python setup.py build_ext --inplace --compiler=mingw32 --fcompiler=gfortran 
  - python setup.py install

test_script:
  - python -c 'import timml; timml.version.__version__;'
