# Modified https://github.com/timcera/wdmtoolbox/blob/master/appveyor.yml

clone_depth: 50

cache:
  - '%LOCALAPPDATA%\pip\Cache'
  - '%USERPROFILE%\.cache\matplotlib'

environment:
  matrix:
    - PYTHON: C:\Miniconda35
      PYTHON_VERSION: 3.5
      BUILD_SCRIPT: "CONDA_BUILD"
    - PYTHON: C:\Miniconda36
      PYTHON_VERSION: 3.6
      BUILD_SCRIPT: "CONDA_BUILD"
    - PYTHON: C:\Miniconda35
      PYTHON_VERSION: 3.5
      BUILD_SCRIPT: "PYTHON_BUILD"
    - PYTHON: C:\Miniconda36
      PYTHON_VERSION: 3.6
      BUILD_SCRIPT: "PYTHON_BUILD"
    - PYTHON: C:\Miniconda36
      PYTHON_VERSION: 3.7
      BUILD_SCRIPT: "PYTHON_BUILD"
    - PYTHON: C:\Miniconda36
      PYTHON_VERSION: 3.7
      BUILD_SCRIPT: "CONDA_BUILD"
      
platform:
  - x86
  - x64
  
matrix:
  fast_finish: true

install:
  - if "%PLATFORM%" == "x86" set PATH=%PYTHON%\bin;%PYTHON%\Scripts;%PATH%
  - if "%PLATFORM%" == "x64" set PATH=%PYTHON%-x64\bin;%PYTHON%-x64\Scripts;%PATH%
  # configure conda and install dependencies
  - conda config --set always_yes yes
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda create -q --name python%PYTHON_VERSION% python=%PYTHON_VERSION%
  - activate python%PYTHON_VERSION%
  - conda install -q --name python%PYTHON_VERSION% setuptools numpy scipy matplotlib jupyter pytest conda-build libpython m2w64-toolchain
  - ps: |
     If ($env:BUILD_SCRIPT -eq "PYTHON_BUILD") {
       python.exe setup.py build_ext --inplace --compiler=mingw32 --fcompiler=gfortran
       python.exe setup.py install
     }
  - ps: |
     If ($env:BUILD_SCRIPT -eq "CONDA_BUILD") {
       conda build conda-recipe --numpy 1.15
       conda install timml --use-local
     }

test_script:
  - pytest tests/test_import.py
  
build: off
