sudo: required
language: python

matrix:
  include:
   - os: linux
     python: "3.5"
     env: BUILD_SCRIPT=COND_BUILD
   - os: linux
     python: "3.5"
     env: BUILD_SCRIPT=PYTHON_BUILD         
   - os: linux
     python: "3.6"
     env: BUILD_SCRIPT=CONDA_BUILD
   - os: linux
     python: "3.6"
     env: BUILD_SCRIPT=PYTHON_BUILD
   - os: osx
     language: generic
     python: "3.5"
     env: 
        - TRAVIS_PYTHON_VERSION=3.5
        - BUILD_SCRIPT=PYTHON_BUILD
   - os: osx
     language: generic
     python: "3.5"
     env: 
        - TRAVIS_PYTHON_VERSION=3.5
        - BUILD_SCRIPT=CONDA_BUILD
   - os: osx
     language: generic
     python: "3.6"
     env: 
        - TRAVIS_PYTHON_VERSION=3.6
        - BUILD_SCRIPT=PYTHON_BUILD
   - os: osx
     language: generic
     python: "3.6"
     env: 
        - TRAVIS_PYTHON_VERSION=3.6
        - BUILD_SCRIPT=CONDA_BUILD
  fast_finish: true

addons:
  apt:
    packages:
     - gfortran

# Setup anaconda
before_install:
  - if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then 
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; 
      then 
        for pkg in gcc; do
          if brew list -1 | grep -q "^${pkg}\$"; then
            brew outdated $pkg || brew upgrade $pkg;
          else
            brew install $pkg;
            brew link --overwrite $pkg;
          fi
        done
      fi

  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes
  - conda config --add channels conda-forge
  - conda update --quiet conda
  # Avoid noise from matplotlib
  - mkdir -p $HOME/.config/matplotlib
  - conda install -q python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib jupyter pytest conda-build anaconda anaconda-client
  - conda info -a

install:
  - if [ "$BUILD_SCRIPT" = "PYTHON_BUILD" ]; then 
      python setup.py install; 
    fi
  - if [ "$BUILD_SCRIPT" = "CONDA_BUILD" ]; then 
      conda build conda-recipe --numpy 1.12;
      conda install timml --use-local; 
    fi
  
script: 
  - pytest
