os:
  - linux
  - osx

sudo: required
language: python
  
matrix:
  fast_finish: true
  python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.5"
  - "3.6"

addons:
  apt:
   packages:
   - gfortran

# Setup anaconda
before_install:
  - if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then 
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda config --set always_yes yes
  - conda update --quiet conda
  # Fix for headless TravisCI
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # Avoid noise from matplotlib
  - mkdir -p $HOME/.config/matplotlib
  - conda create --yes --quiet -n timml python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib
  - source activate timml

install:
  - python setup.py build_ext --inplace
  - python setup.py install
  
script:
  - python -c 'import timml; timml.version.__version__;'
