os:
  - linux
  - osx

sudo: required
language: python

env:
  # Default values for common package
  global:
    - COVERAGE=false
    - USEMPL=true
    - MATPLOTLIB=

matrix:
  fast_finish: true
  include:
  - python: 2.7
    env:
    - PYTHON=3.6
    - NUMPY=
    - SCIPY=
    - MATPLOTLIB=

addons:
  apt:
   packages:
   - gfortran

# Setup anaconda
before_install:
  - if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then 
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda config --set always_yes yes
  - conda update --quiet conda
  # Fix for headless TravisCI
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # Avoid noise from matplotlib
  - mkdir -p $HOME/.config/matplotlib
  - SRCDIR=$PWD
  # Build package list to avoid empty package=versions; only needed for versioned packages
  - PKGS="python=${PYTHON}"
  - PKGS="${PKGS} numpy"; if [ ${NUMPY} ]; then PKGS="${PKGS}=${NUMPY}"; fi
  - PKGS="${PKGS} scipy"; if [ ${SCIPY} ]; then PKGS="${PKGS}=${SCIPY}"; fi
  - if [ ${USEMPL} = true ]; then PKGS="${PKGS} matplotlib"; if [ ${MATPLOTLIB} ]; then PKGS="${PKGS}=${MATPLOTLIB}"; fi; fi
  - conda create --yes --quiet -n timml ${PKGS}
  - source activate timml
  - export SRCDIR=$PWD

install:
  - python setup.py build_ext --inplace
  - python setup.py install
  
script:
  - python -c 'import timml; timml.version.__version__;'
