sudo: required
language: python

matrix:
  include:
   - os: linux
     python: "3.5"
   - os: linux
     python: "3.6"
   - os: osx
     language: generic
     python: "3.5"
     env: TRAVIS_PYTHON_VERSION=3.5
   - os: osx
     language: generic
     python: "3.6"
     env: TRAVIS_PYTHON_VERSION=3.6
  fast_finish: true

addons:
  apt:
    packages:
     - gfortran

# Setup anaconda
before_install:
  - if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then 
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; 
      then 
        for pkg in gcc; do
          if brew list -1 | grep -q "^${pkg}\$"; then
            brew outdated $pkg || brew upgrade $pkg;
          else
            brew install $pkg;
          fi
        done
      fi

  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes
  - conda update --quiet conda
  # Avoid noise from matplotlib
  - mkdir -p $HOME/.config/matplotlib
  - conda create --yes --quiet -n timml python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib
  - source activate timml

install:
  - python setup.py build_ext --inplace
  - python setup.py install
  
script:
  - python -c 'import timml; timml.version.__version__;'
