environment:
  matrix:
    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.6.2"
      PYTHON_ARCH: "64"

platform:
    - x64

install:
    - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod 
      https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50.builds | 
      Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) {
        throw "There are newer queued builds for this pull request, failing early." }

build_scipt:
  - conda config --set always_yes yes
  - conda update conda --quiet
  - ps: conda install numpy sicpy matplotlib --quiet
  - python setup.py build_ext --inplace
  - python setup.py install

test_script:
  - python -c 'import timml; timml.version.__version__;'
