environment:
  matrix:
    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.6.2"
      PYTHON_ARCH: "64"

platform:
    - x64

build_scipt:
  - conda config --set always_yes yes
  - conda update conda --quiet
  - ps: conda install numpy sicpy matplotlib --quiet
  - python setup.py build_ext --inplace
  - python setup.py install

test_script:
  - python -c 'import timml; timml.version.__version__;'
