environment:
  matrix:
    - PYTHON_VERSION: 3.5
      MINICONDA: C:\Miniconda3-x64
      PYTHON_ARCH: "64"

    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda3-x64
      PYTHON_ARCH: "64"

    - PYTHON_VERSION: 3.5
      MINICONDA: C:\Miniconda3
      PYTHON_ARCH: "32"

    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda3
      PYTHON_ARCH: "32"

matrix:
  fast_finish: true

init:
  - ECHO "Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""

  - "ECHO %PYTHON_VERSION% %MINICONDA%"

build_script:
  - ps: set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%
  - conda config --set always_yes yes
  - conda update conda --quiet
  - ps: conda create -q -n timml_env python=%PYTHON_VERSION% numpy scipy matplotlib toolchain mingw setuptools
  - activate timml_env
  - python setup.py config_fc
  - python setup.py config --compiler=mingw32 --fcompiler=gfortran
  - python setup.py build_ext --inplace 
  - python setup.py install

test_script:
  - python -c 'import timml; timml.version.__version__;'
